version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme%
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    volumes:
      - ./logs:/var/log/nginx
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme%
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme%
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data:
  nginx_logs:
